version: '3.8'
services:
# Traefik configuration

    traefik:
        image: 'traefik:2.5'
        container_name: 'traefik'
        restart: 'unless-stopped'
        ports:
            - '80:80'
            - '8080:8080'
            - '443:443'

        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './traefik/traefik.toml:/traefik.toml'
            - './traefik/traefik_dynamic.toml:/traefik_dynamic.toml'
            - './letsencrypt:/letsencrypt'
            - './traefik/usersfile.txt:/usersfile.txt'

        networks:
            - web

# Whoami test configuration. Remove later
    whoami:
        image: 'traefik/whoami'
        restart: 'unless-stopped'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.whoami.rule=Host(`whoami.jeppe.science`)'
            - 'traefik.http.services.whoami.loadbalancer.server.port=80'
            - 'traefik.http.routers.whoami.entrypoints=websecure'
            # - 'traefik.http.routers.whoami.middlewares=simpleAuth@file'
            - 'traefik.http.routers.whoami.tls.certresolver=letsencrypt'
        networks:
            - web

networks:
    web:
        external: true