version: '3'
services:
  homeassistant:
    image: linuxserver/homeassistant
    container_name: homeassistant
    hostname: homeassistant
    volumes:
      - ./volumes/homeassistant/config:/config
    restart: unless-stopped

    ports:
      - 8123

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen

    networks:
      - default
      - web
    # privileged: true
    # network_mode: host

    labels:
      traefik.enable: "true"

      traefik.http.routers.homeassistant.rule: "Host(`assistant.jeppe.science`)"
      traefik.http.routers.homeassistant.entrypoints: "websecure"
      traefik.http.routers.homeassistant.tls.certresolver: "letsencrypt"

networks:
  web:
    external: true