version: "3"


services:
  traefik:
    image: 'traefik:2.9'
    container_name: 'traefik'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'

    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik.toml:/traefik.toml'
      - './traefik_dynamic.toml:/traefik_dynamic.toml'
      - './usersfile.txt:/usersfile.txt'
      - '../letsencrypt:/letsencrypt'

    networks:
      - web

networks:
  web:
    external: true